# Generated by Django 5.1.6 on 2025-11-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_flag_content_type_flag_object_id_flag_resolved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('population', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.county'),
        ),
        migrations.CreateModel(
            name='Rumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rumor_id', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('sentiment', models.CharField(max_length=10)),
                ('score', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('related_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.county')),
                ('related_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
            ],
        ),
    ]
